module I2S_Master (
    input  logic              clk,         // System clock (e.g., 50 MHz)
    input  logic              rst_n,       // Active-low reset
    input  logic [15:0]       audio_data,  // Parallel 16-bit audio sample to transmit
    input  logic              new_sample,  // Signal to load new audio sample
    output logic              mclk,        // Master clock (e.g., 12.5 MHz)
    output logic              bclk,        // Bit clock (e.g., 3.125 MHz)
    output logic              lrclk,       // Left/right clock (determines active channel)
    output logic              sdata        // Serial audio data output
);

  // Clock dividers to generate mclk, bclk, and lrclk.
  // For example: if clk=50MHz, mclk can be generated by dividing by 4 (12.5MHz).
  // Then bclk can be mclk divided by 4 (3.125MHz).
  logic [1:0] mclk_div;
  logic [2:0] bclk_div;
  logic [9:0] sample_cnt;  // Counter for sample period (e.g., 32 or 64 BCLK cycles)

  // Shift register for serial data output.
  logic [15:0] tx_shift;
  logic [4:0]  bit_cnt;  // Count 0 to 31

 

endmodule
